//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarsInventory()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CarNumber { get; set; }
        public int CarPriceListId { get; set; }
        public int Mileage { get; set; }
        public bool IsValid { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual CarPriceList CarPriceList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
