//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public System.DateTime ActualReturnDate { get; set; }
        public int TZ { get; set; }
        public int CarNumber { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CarsInventory CarsInventory { get; set; }
        public virtual User User { get; set; }
    }
}
